name : complex-workflow

on : push

jobs : 
    use-ubuntu :
        name : ubunut-sys
        runs-on : ubuntu-latest
        steps :
            - name : step one
              run : date
    use-windows :
        name : windows-sys
        runs-on : windows-latest
        steps :
            - name : get-date
              run : Get-Date
    use-mac :
        needs : [use-windows,use-ubuntu]
        name : mac-sys
        runs-on : mac-latest
        steps :
            - name : get-date
              run : echo date